// This file is autogenerated. Changes will be overwritten.
#include <UVLADIE3JM/moc_DiscordRPC.cpp>
#include <UVLADIE3JM/moc_EmulatorCore.cpp>
#include <UVLADIE3JM/moc_IEmulatorCore.cpp>
#include <EKFF6VPWT7/moc_JaguarSystem.cpp>
#include <LOGJ4MT3G7/moc_LynxSystem.cpp>
#include <YPKJ5OE7LN/moc_AboutDialog.cpp>
#include <YPKJ5OE7LN/moc_ControllerSettingsDialog.cpp>
#include <YPKJ5OE7LN/moc_CoverDownloadDialog.cpp>
#include <YPKJ5OE7LN/moc_DebugWindow.cpp>
#include <YPKJ5OE7LN/moc_DisplayWidget.cpp>
#include <GBTPFG5N3J/moc_GameListModel.cpp>
#include <GBTPFG5N3J/moc_GameListWidget.cpp>
#include <YPKJ5OE7LN/moc_JaguarIntroWidget.cpp>
#include <YPKJ5OE7LN/moc_MainWindow.cpp>
#include <YPKJ5OE7LN/moc_OverlayWidget.cpp>
#include <YPKJ5OE7LN/moc_SettingsDialog.cpp>
#include <YPKJ5OE7LN/moc_WelcomeDialog.cpp>
